// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAPI.Data;

#nullable disable

namespace WeatherAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherAPI.Models.ForecastCache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CacheId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForecastJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheId");

                    b.ToTable("ForecastCaches");
                });

            modelBuilder.Entity("WeatherAPI.Models.HourlyCache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CacheId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HourlyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheId");

                    b.ToTable("HourlyCaches");
                });

            modelBuilder.Entity("WeatherAPI.Models.HourlyWeatherCache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CacheId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HourlyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheId");

                    b.ToTable("HourlyWeatherCaches");
                });

            modelBuilder.Entity("WeatherAPI.Models.WeatherCache", b =>
                {
                    b.Property<int>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CacheId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheId");

                    b.ToTable("WeatherCaches");
                });
#pragma warning restore 612, 618
        }
    }
}
